package com.digithink.zsretail.erp.enumeration;

/**
 * Enumerates the supported ERP synchronization operations.
 */
public enum ErpSyncOperation {
	IMPORT_ITEM_FAMILIES, IMPORT_ITEM_SUBFAMILIES, IMPORT_ITEMS, IMPORT_ITEM_BARCODES, IMPORT_LOCATIONS,
	IMPORT_CUSTOMERS, IMPORT_SALES_PRICES, IMPORT_SALES_DISCOUNTS, EXPORT_CUSTOMER, EXPORT_TICKET, EXPORT_TICKET_LINE, UPDATE_TICKET, EXPORT_PAYMENT_HEADER,
	EXPORT_PAYMENT_LINE, EXPORT_RETURN, EXPORT_RETURN_LINE, UPDATE_RETURN, EXPORT_SESSION, SYNC_ERP_DELETIONS
}
