spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=pos_db_test
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

application.standalone=false

erp.dynamicsnav.enabled=true
erp.dynamicsnav.base-url=http://192.168.10.166:24/test4/ODataV4
erp.dynamicsnav.company=005-SCPC
erp.dynamicsnav.domain=Groupe-Hammami
erp.dynamicsnav.username=POS
erp.dynamicsnav.password=SCPC**2026**

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true


pos.pricing.enable-sales-price-group=true
erp.sync.enabled=true
erp.sync.scheduler.delay=10000

app.upload.dir=C:/uploads/pos-images
logging.file.name=C:/zsretail-test/backend.log